global:
  scrape_interval: 1s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['individuals-api:8081', 'person-service:8082']

  - job_name: grafana
    static_configs:
      - targets: [ 'grafana:3000' ]

  - job_name: alloy
    static_configs:
      - targets: [ 'alloy:9080' ]

  - job_name: loki
    static_configs:
      - targets: [ 'loki:3100' ]